/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbordagemRouteImport } from './routes/abordagem'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CriteriosRouteImport } from './routes/criterios'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProblemaRouteImport } from './routes/problema'
import { Route as ServicosRouteImport } from './routes/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbordagemRoute = AbordagemRouteImport.update({
  id: '/abordagem',
  path: '/abordagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriosRoute = CriteriosRouteImport.update({
  id: '/criterios',
  path: '/criterios',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemaRoute = ProblemaRouteImport.update({
  id: '/problema',
  path: '/problema',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abordagem': typeof AbordagemRoute
  '/contacto': typeof ContactoRoute
  '/criterios': typeof CriteriosRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/problema': typeof ProblemaRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abordagem': typeof AbordagemRoute
  '/contacto': typeof ContactoRoute
  '/criterios': typeof CriteriosRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/problema': typeof ProblemaRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abordagem': typeof AbordagemRoute
  '/contacto': typeof ContactoRoute
  '/criterios': typeof CriteriosRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/problema': typeof ProblemaRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abordagem'
    | '/contacto'
    | '/criterios'
    | '/metodo'
    | '/privacidade'
    | '/problema'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abordagem'
    | '/contacto'
    | '/criterios'
    | '/metodo'
    | '/privacidade'
    | '/problema'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/abordagem'
    | '/contacto'
    | '/criterios'
    | '/metodo'
    | '/privacidade'
    | '/problema'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbordagemRoute: typeof AbordagemRoute
  ContactoRoute: typeof ContactoRoute
  CriteriosRoute: typeof CriteriosRoute
  MetodoRoute: typeof MetodoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProblemaRoute: typeof ProblemaRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abordagem': {
      id: '/abordagem'
      path: '/abordagem'
      fullPath: '/abordagem'
      preLoaderRoute: typeof AbordagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criterios': {
      id: '/criterios'
      path: '/criterios'
      fullPath: '/criterios'
      preLoaderRoute: typeof CriteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problema': {
      id: '/problema'
      path: '/problema'
      fullPath: '/problema'
      preLoaderRoute: typeof ProblemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbordagemRoute: AbordagemRoute,
  ContactoRoute: ContactoRoute,
  CriteriosRoute: CriteriosRoute,
  MetodoRoute: MetodoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProblemaRoute: ProblemaRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
